import { UploaderInput, UploadResult, IModule } from '../types';
import { Buffer } from 'buffer';

/**
 * Phase 6: Uploader & Scheduler (Real Implementation)
 */
export class UploaderScheduler implements IModule<UploaderInput, UploadResult> {
  name = "Uploader & Scheduler";
  description = "Uploads video to YouTube via API and configures release schedule.";

  async execute(input: UploaderInput): Promise<UploadResult> {
    if (!input.video_asset || input.video_asset.status !== 'generated') {
      throw new Error("Invalid video asset.");
    }

    if (typeof window !== 'undefined' || !process.env.GOOGLE_CLIENT_ID) {
      return this.uploadSimulated(input);
    }

    return this.uploadReal(input);
  }

  private async uploadReal(input: UploaderInput): Promise<UploadResult> {
    // Server-side only imports
    const { google } = await import('googleapis');
    const { Readable } = await import('stream');

    const oauth2Client = new google.auth.OAuth2(
      process.env.GOOGLE_CLIENT_ID,
      process.env.GOOGLE_CLIENT_SECRET,
      process.env.GOOGLE_REDIRECT_URI
    );

    oauth2Client.setCredentials(input.authCredentials!);
    const service = google.youtube({ version: 'v3', auth: oauth2Client });

    const base64Data = input.video_asset.video_url.split(';base64,').pop();
    if (!base64Data) throw new Error("Invalid Video URL");
    const buffer = Buffer.from(base64Data, 'base64');
    
    const stream = new Readable();
    stream.push(buffer);
    stream.push(null);

    try {
      const response = await service.videos.insert({
        part: ['snippet', 'status'],
        requestBody: {
          snippet: {
            title: input.metadata.title_template,
            description: input.metadata.description_template + "\n\nGenerated by AI Automation #Shorts",
            categoryId: '28'
          },
          status: {
            privacyStatus: input.schedule.privacy_status,
            publishAt: input.schedule.publish_at
          }
        },
        media: {
          body: stream,
          mimeType: 'video/mp4'
        }
      });

      return {
        platform: 'youtube',
        video_id: response.data.id || 'unknown',
        platform_url: `https://youtube.com/shorts/${response.data.id}`,
        status: input.schedule.publish_at ? 'scheduled' : 'uploaded',
        scheduled_for: input.schedule.publish_at,
        uploaded_at: new Date().toISOString()
      };
    } catch (error: any) {
      throw new Error(`YouTube API Upload Failed: ${error.message}`);
    }
  }

  private async uploadSimulated(input: UploaderInput): Promise<UploadResult> {
    await new Promise(resolve => setTimeout(resolve, 1000));
    return {
      platform: 'youtube',
      video_id: "dQw4w9WgXcQ",
      platform_url: "https://youtube.com/shorts/dQw4w9WgXcQ",
      status: input.schedule.publish_at ? 'scheduled' : 'uploaded',
      scheduled_for: input.schedule.publish_at,
      uploaded_at: new Date().toISOString()
    };
  }
}